config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 100 },
             format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :department, length: { in: 3..50 }, allow_blank: true
    has_many :attendances, dependent: :destroy

  def self.search(search)
      if search
        where(['name LIKE ?', "%#{search}%"])
      else
          all
      end
  end
  def self.import(file)
      user = find_by(email: row["email"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
  end
  def self.updatable_attributes
      ["name", "email",]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit, :update]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user, only: [:destroy, :index, :edit_basic_info, :update_basic_info]
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
    respond_to do |format|
      format.html
      format.csv do
        send_data render_to_string, filename: "products.csv", type: :csv
      end
    end
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
  end
  
  def import
    User.import(params[:file])
    redirect_to users_url
  end
  def destroy
    User.find(params[:id]).delete
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user
    else
      render 'edit_basic_info'
    end
  end
    private
      def user_params
        params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
      end
      def logged_in_user
        unless logged_in?
          flash[:danger] = "ログインしてください。"
          redirect_to login_url
        end
      end
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless @user == current_user
      end
      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
      def basic_info_params
        params.require(:user).permit(:basic_time, :work_time)
      end
end

app/helpers/users_helper.rb
module UsersHelper
    def format_basic_time(datetime)
        format("%.2f", ((datetime.hour * 60) + datetime.min) /60.0)
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :所属 %>
  <%= f.text_field :affiliation, class: 'form-control' %>
  
  <%= f.label :社員番号 %>
  <%= f.number_field :employee_number, class: 'form-control' %>
  
  <%= f.label :カードID %>
  <%= f.text_field :uid, class: 'form-control' %>
  
  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label :基本時間 %>
  <%= f.time_field :basic_work_time, class: 'form-control' %>

  <%= f.label :指定勤務開始時間 %>
  <%= f.time_field :designated_work_start_time, class: 'form-control' %>

  <%= f.label :指定勤務終了時間 %>
  <%= f.time_field :designated_work_end_time, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %><br>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, method: :delete, date: { confirm: "削除してもよろしいですか？" }, class: "btn btn-primary" %><br>
    | <%= link_to "編集", basic_info_path(user), class: "btn btn-primary" %>
  <% else %>
    | <%= link_to "編集", basic_info_path(user), class: "btn btn-primary" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント情報の更新') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>

      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<% if params[:search].nil? %>
  <h1>ユーザー一覧</h1>
<% else %>
  <h1>検索結果</h1>
<% end %>

<div class="container">
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "CSVをインポート", class: "btn btn-primary" %>
  <% end %>


<ul class="users">
  <%= render @users %>
</ul>


</div>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成') %>
<h1>新規作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
    <table class="table-bordered table-condensed">
        <tr>
            <td>
                <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month}),
                                 class: "btn btn-xs btn-primary" %>
                &emsp;<%= @first_day.to_s(:year_month) %> 時間管理表&emsp;
                <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month}),
                                 class: "btn btn-xs btn-primary" %>
            </td>
            <td>指定勤務開始時間 <!--<%= format_basic_time(@user.work_time) %>--><br>
                指定勤務終了時間
            </td>
            <td colspan = "3">基本時間 <!--<%= format_basic_time(@user.basic_time) %>--></td>
            <td>初日 <%= @first_day.to_s(:date) %></td>
        </tr>
        <tr>
            <td>所属 : <%= @user.department.present? ? @user.department : "未設定" %></td>
            <td>氏名 : <%= @user.name %></td>
            <td>コード</td>
            <td>555</td>
            <td>出勤日数 : <%= @worked_sum %>日</td>
            <td>末日 <%= @last_day.to_s(:date) %></td>
        </tr>
    </table>
【所属長承認申請のお知らせ】<br>
【勤怠変更申請のお知らせ】<br>
【残業申請のお知らせ】<br>

    <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
    <%= link_to "csv出力",user_path(@user, format: :csv), class: "btn btn-primary" %><br>
    <%= link_to "勤怠修正ログ（承認済）", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
    <table class = "table-bordered table-striped table-condensed">
        <thead>
            <tr>　<!-- rowspan:縦結合、colspan:横結合-->
                <th rowspan = "3">残業申請</th>
                <th rowspan = "3">日付</th>
                <th rowspan = "3">曜日</th>
                <th colspan = "8">【実績】</th>
                <th colspan = "8">所定外勤務</th>
            </tr>
            <tr>
                <th colspan = "3">出社</th>
                <th colspan = "3">退社</th>
                <th rowspan = "2">在社時間</th>
                <th rowspan = "2">備考</th>
                <th colspan = "2">終了予定時間</th>
                <th rowspan = "2">時間外時間</th>
                <th rowspan = "2">業務処理内容</th>
                <th rowspan = "2">指示者確認印</th>
            </tr>
            <tr>
                <th>時</th>
                <th>分</th>
                <th></th>
                <th>時</th>
                <th>分</th>
                <th></th>
                <th>時</th>
                <th>分</th>
            </tr>
        <tbody>
          <% @dates.each do |day| %>
            <tr>
                <th><%= link_to "残業申請", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %></th>
                <td><%= day.worked_on.to_s(:date) %></td>
                <% if %w{日 月 火 水 木 金 土}[day.worked_on.wday] == "日" %>
                  <td class="red"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                <% elsif %w{日 月 火 水 木 金 土}[day.worked_on.wday] == "土" %>
                  <td class="blue"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                <% else %>
                  <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                <% end %>
                <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
                <td><%= day.started_at.round_to(15.minutes).to_s(:min) if day.started_at.present? %></td>
                <td>
                    <% if day.worked_on == Date.today && day.started_at.nil? %>
                      <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
                    <% end %>
                </td>
                <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
                <td><%= day.finished_at.round_to(15.minutes).to_s(:min) if day.finished_at.present? %></td>
                <td>
                    <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? %>
                      <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
                    <% end %>
                </td>
                <td>
                    <% if day.started_at.present? && day.finished_at.present? %>
                      <%= working_times(day.started_at, day.finished_at) %>
                      <% seconds = (day.finished_at - day.started_at).to_i %>
                      <% @total_seconds = @total_seconds.to_i + seconds %>
                    <% end %>
                </td>
                <td><%= day.note %></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td colspan = "2"></td>
                <td colspan = "6"></td>
                <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
                <td colspan = "5"></td>
                <td>所属長承認　未<br>
                    <%= link_to "", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %><br>
                    <br>
                    <%= link_to "残業申請", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
                </td>
            </tr>
        </tfoot>
      </thead>
    </table>
</div>