config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  resources :users do
    resources :attendances, only: :create
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :worked_on, presence: true
  before_save :started_at_should_present
  validate :started_at_should_early_than_finished_at
  private
  
    def started_at_should_present
      errors.add(:finished_at, ": 出勤時間が打刻されていません。") if self.started_at.nil?
    end
    def started_at_should_early_than_finished_at
      if started_at && working_times(started_at, finished_at).to_i < 0
        errors.add(:finished_at, ": 退勤時間が正しくありません。")
      end
    end
    def working_times(started_at, finished_at)
        format("%.2f", (((finished_at.round_to(15) - started_at.round_to(15)) / 60) /60.0 )) if finished_at
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @attendance = @user.attendances.find_by(worked_on: Date.today)
        if @attendance.started_at.nil?
          @attendance.update_attributes(started_at: current_time)
          flash[:info] = 'おはようございます。'
        elsif @attendance.finished_at.nil?
          @attendance.update_attributes(finished_at: current_time)
          flash[:info] = 'おつかれさまでした。'
        else
          flash[:danger] = 'トラブルがあり、登録出来ませんでした。'
        end
        redirect_to @user
    end
    def edit
      @user = User.find(params[:id])
      @first_day = first_day(params[:date])
      @last_day = @first_day.end_of_month
      @dates = user_attendances_month_date
    end
    def update
      @user = User.find(params[:id])
      @attendance = @user.attendances.find_by(worked_on: Date.today)
      if attendances_invalid?
       attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes(item)
       end
       flash[:success] = '勤怠情報を更新しました。'
       redirect_to user_url(@user, params:{first_day: params[:date]})
      else
       flash[:danger] = "不正な時間入力がありました、再入力してください。"
       redirect_to edit_attendances_path(@user, params[:date]) and return
      end
    end
      private
        def attendances_params
          params.permit(attendances: [:started_at, :finished_at, :note])[:attendances]
        end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
    def current_time
        Time.new(
            Time.now.year,
            Time.now.month,
            Time.now.day,
            Time.now.hour,
            Time.now.min,0)
    end
    def working_times(started_at, finished_at)
        format("%.2f", (((finished_at.round_to(15) - started_at.round_to(15)) / 60) /60.0 ))
    end
    def working_times_sum(seconds)
        format("%.2f", seconds / 60 / 60.0)
    end
    def first_day(date)
     !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
    end

    def user_attendances_month_date
     @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
    end
    
    def attendances_invalid?
      attendances = true
      attendances_params.each do |id, item|
        if item[:started_at].blank? && item[:finished_at].blank?
          next
        elsif item[:started_at].blank? || item[:finished_at].blank?
          attendances = false
          break
        elsif item[:started_at] > item[:finished_at]
          attendances = false
          break
        end
      end
      return attendances
    end
end

app/views/attendances/edit.html.erb
<% provide(:title, "勤怠編集") %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: update_attendances_path, method: :patch) do |f| %>
    <table class = "table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>出社</th>
                <th>退社</th>
                <th>在社時間</th>
                <th>備考</th>
            </tr>
        </thead>
        <tbody>
          <% @dates.each do |day| %>
            <%= fields_for "attendances[]", day do |af| %> 
             <tr>
                <td><%= day.worked_on.to_s(:date) %></td>
                <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
                <% if day.worked_on <= Date.today %>
                 <td><%= af.time_field :started_at, class: "form-control" %></td>
                 <td><%= af.time_field :finished_at, class: "form-control" %></td>
                <% else %>
                 <td></td>
                 <td></td>
                <% end %>
                <td>
                  <% if day.started_at.present? && day.finished_at.present? %>
                    <%= working_times(day.started_at, day.finished_at) %>
                  <% end %>
                </td>
                <td><%= af.text_field :note, class: "form-control" %></td>
              </tr> 
          <% end %>
         <% end %>
        </tbody>
    </table>
   <div class="container"> 
    <div class="row">
      <div class = "btn-attendances-update">
       <div class="col-xs-6 form-inline">
        <%= f.submit "編集を保存する", class: "btn btn-primary btn-edit" %>
       </div> 
       <div class="col-xs-6 form-inline">
        <%= link_to "キャンセル", user_path(@user, params:{first_day: @firstday}), class: "btn btn-default btn-block btn-cansel" %>
       </div>
      </div>
     </div>
   </div> 
  <% end %>
</div>